export default {
  South: {
    Gisagara: {
      Gikonko: {
        Cyiri: [
          'Curusi',
          'Cyendajuru',
          'Cyimpuga',
          'Katiro',
          'Kigitega',
          'Kinyana',
          'Murambi',
          'Musambi',
          'Sanzu',
        ],
        Gasagara: [
          'Agasenyi',
          'Karukambira',
          'Bibungo',
          'Gasagara',
          'Karehe',
          'Mugusa',
          'Remera',
          'Mubezi',
        ],
        Gikonko: ['Gahabwa', 'Karubondo', 'Manyinya', 'Rugarama', 'Runyinya'],
        Mbogo: [
          'Bukorota',
          'Buremera',
          'Kirivuga',
          'Mbogo',
          'Nyakabuye',
          'Nyiramageni',
          'Rwatano',
          'Rwintare',
        ],
      },
      Gishubi: {
        Gabiro: [
          'Busave',
          'Kigozi',
          'Kivugiza',
          'Kurugogwe',
          'Nyamure',
          'Nyundo',
          'Ruhina',
          'Kurutare',
          'Rweza',
          'Tamba',
          'Zamwe',
        ],
        Nyabitare: [
          'Hemba',
          'Kabuga',
          'Kanombe',
          'Mutobo',
          'Mwiba',
          'Ndaro',
          'Nyabisindu',
          'Nyirakanywero',
          'Rwinkwavu',
          'Ryarugaju',
        ],
        Nyakibungo: [
          'Banga',
          'Gicaca',
          'Kavumu',
          'Kibindyi',
          'Munyinya',
          'Nkunamo',
          'Nyakibungo',
          'Nyarurama',
          'Rebero',
          'Rugarama',
          'Rusasa',
        ],
        Nyeranzi: [
          'Cyamanyeri',
          'Gikuyo',
          'Gishya',
          'Gitekateke',
          'Kabungo',
          'Kagoma',
          'Kavumu',
          'Kigarama',
          'Muduha',
          'Muyinza',
          'Nyabyunyu',
          'Rebero',
          'Rugogwe',
          'Rwanza',
          'Rwegura',
          'Sakara',
        ],
      },
      Kansi: {
        Akaboti: [
          'Agacyamu',
          'Agataba',
          'Akabuga',
          'Akayenzi',
          'Gatare',
          'Impinga',
          'Rugarama',
          'Ruhuha',
        ],
        Bwiza: [
          'Akakinka',
          'Akambogo',
          'Gitwa',
          'Kimanama',
          'Mbeho',
          'Nyakibungo',
          'Nyaruhengeri',
        ],
        Sabusaro: [
          'Akayenzi',
          'Gikore',
          'Muhororo',
          'Nyamure',
          'Nyarunazi',
          'Ruhangaye',
        ],
        Umunini: [
          'Agatare',
          'Akabagari',
          'Gisororo',
          'Kaburanjwiri',
          'Kaduha',
          'Kamugani',
          'Kigarama',
          'Nyange',
        ],
      },
      Kibirizi: {
        Duwani: [
          'Buhoro',
          'Burashi',
          'Cyahafi',
          'Duwani',
          'Karambo',
          'Kinteko',
          'Kivumu',
          'Mubuga',
          'Murambi',
          'Rwuya',
          'Taba',
        ],
        Kibirizi: [
          'Burashi',
          'Gasagara',
          'Kabakobwa',
          'Kigarama',
          'Mareba',
          'Mbeho',
          'Ruhuha',
          'Shenyeri',
          'Torero',
        ],
        Muyira: [
          'Agahumiro',
          'Agasharu',
          'Akagarama',
          'Akayohani',
          'Akirasaniro',
          'Impinga',
          'Nyagasozi',
          'Nyagisasa',
          'Rwinzuki',
          'Itaba',
          'Zihare',
        ],
        Ruturo: [
          'Agatongati',
          'Akabuhuzu',
          'Akamuzenga',
          'Akarugaju',
          'Impinga',
          'Kabagoti',
          'Karengera',
          'Kigarama',
          'Ntobo',
          'Nyabununi',
          'Rubazi',
        ],
      },
      Kigembe: {
        Agahabwa: [
          'Agahehe',
          'Kabacuzi',
          'Kamutozo',
          'Kamweko',
          'Nyamabuye',
          'Ruhuha',
          'Taba',
        ],
        Gatovu: [
          'Agasharu',
          'Agatare',
          'Akamana',
          'Gitozo',
          'Janja',
          'Kigarama',
          'Taba',
        ],
        Impinga: [
          'Akadogo',
          'Akakijugujugu',
          'Ikidashya',
          'Icyijana',
          'Nyamirama',
          'Rugeragere',
        ],
        Nyabikenke: [
          'Akabahizi',
          'Akimbaka',
          'Impinga',
          'Rutare',
          'Rutaza',
          'Shyombo',
          'Umurangara',
          'Ruyenzi',
        ],
        Rubona: [
          'Akadogo',
          'Kashyaga',
          'Gaharanyonga',
          'Gatongati',
          'Murehe',
          'Nyakabuye',
        ],
        Rusagara: [
          'Agasharu',
          'Akajwiga',
          'Akatera',
          'Kigarama',
          'Nyarukurazo',
          'Nyarunyinya',
        ],
      },
      Mamba: {
        Gakoma: [
          'Gakomeye',
          'Gatare',
          'Kinamba',
          'Kivomo',
          'Kizenga',
          'Rebero',
          'Rugenge',
          'Rugwiza',
          'Ruhuha',
          'Sokofi',
        ],
        Kabumbwe: [
          'Buye',
          'Gahararo',
          'Kabuga',
          'Kirwa',
          'Muhabura',
          'Munopfu',
          'Nunga',
          'Nyarugenge',
        ],
        Mamba: [
          'Buhima',
          'Gakoma',
          'Gatovu',
          'Kamudogo',
          'Karama',
          'Kirase',
          'Mashenyi',
          'Nyarugenge',
          'Rugunga',
        ],
        Muyaga: [
          'Butezi',
          'Cadi',
          'Cyarwa',
          'Kabeza',
          'Kibumba',
          'Mutori',
          'Nyamirama',
          'Ruhamagariro',
          'Shyembe',
        ],
        Ramba: [
          'Gatare',
          'Gatoke',
          'Kayenzi',
          'Kigangazi',
          'Murama',
          'Murambi',
          'Nyiramageni',
          'Runazi',
          'Rurama',
          'Rusave',
          'Rwimvubu',
        ],
      },
      Muganza: {
        Cyumba: [
          'Byiza',
          'Cyumba',
          'Gitwa',
          'Kabacuzi',
          'Kamabango',
          'Musatsi',
          'Mutorerwa',
          'Nyagatovu',
          'Nyiraburiba',
          'Rugantete',
          'Rutare',
          'Rwimisambi',
        ],
        Muganza: [
          'Agasharu',
          'Agatongati',
          'Amajuri',
          'Cyanamo',
          'Gitisi',
          'Rwamugoyi',
          'Rwinkuba',
          'Ubusenyi',
          'Urusaro',
        ],
        Remera: [
          'Agakurwe',
          'Agaseke',
          'Akarambo',
          'Butare',
          'Akajyanama',
          'Taba',
        ],
        Rwamiko: [
          'Agasharu',
          'Agatovu',
          'Akarubumba',
          'Akimirama',
          'Ubuseruka',
          'Gako',
          'Impinga',
          'Kabahongo',
          'Kiberengeri',
          'Kidaturwa',
          'Kigina',
          'Kiyogoro',
          'Mbehe',
          'Nyagatovu',
          'Nyamagana',
          'Ryarumenangiga',
          'Umunazi',
        ],
        Saga: [
          'Akabacuzi',
          'Bucaya',
          'Buhiza',
          'Duwane',
          'Impinga',
          'Isangano',
          'Kanto I',
          'Kanto II',
          'Nyabigugu',
          'Nyagafumberi',
          'Nyakagezi',
          'Nyamiheto I',
          'Nyamiheto II',
          'Rwinkuba',
        ],
      },
      Mugombwa: {
        Baziro: [
          'Banzankuru',
          'Gitungwa',
          'Nyabinyenga',
          'Nyagatovu',
          'Nyamirama',
          'Nyarukeri',
          'Nyesumo',
        ],
        Kibayi: [
          'Agakanka',
          'Akarutsibuka',
          'Akashyamba',
          'Akabuga',
          'Rinda',
          'Rwahambi',
          'Udukoni',
        ],
        Kibu: ['Agasharu', 'Akabugabo', 'Akagashuma', 'Mushongi', 'Rurenge'],
        Mugombwa: [
          'Agasharu',
          'Akagarama',
          'Akarambo',
          'Bishya',
          'Impinga',
          'Migina',
        ],
        Mukomacara: [
          'Agakomansyo',
          'Akanyamirama',
          'Akarangabo',
          'Akatare',
          'Gitarama',
          'Kabuye',
          'Nyabisonga',
          'Nyarusange',
          'Umukungu',
        ],
      },
      Mukindo: {
        Gitega: [
          'Agasharu',
          'Akazenga',
          'Gatunda',
          'Joma',
          'Akabati',
          'Magi',
          'Nyabikoni',
          'Nyamabuye',
          'Rebero',
          'Ruko',
        ],
        Mukiza: [
          'Akagarama',
          'Bukamba',
          'Cyimana',
          'Gitwa',
          'Kigoyi',
          'Mukiza',
          'Nyabiryo',
          'Nyakazana',
          'Nyarutovu',
          'Rusumba',
        ],
        Nyabisagara: [
          'Agatare',
          'Kabuga',
          'Akanage',
          'Butare',
          'Kamasiga',
          'Makwaza',
          'Mihigo',
          'Mutondo',
          'Nkurubuye',
          'Nyabihama',
          'Rurimbi',
          'Rususa',
        ],
        Runyinya: [
          'Agakomeye',
          'Agasharu',
          'Akakarinda',
          'Akamaranga',
          'Akarugina',
          'Akayenzi',
          'Cyumusave',
          'Impinga',
          'Itaba',
          'Mpungwe',
          'Munyegera',
          'Nyiranguri',
        ],
      },
      Musha: {
        Bukinanyana: [
          'Agatega',
          'Akagarama',
          'Bukinanyana',
          'Gihinga',
          'Karishyira',
          'Kigoma',
          'Mugejuru',
          'Munyegera',
          'Rugarama',
          'Rukoni',
          'Rwabuhanga',
          'Rwatano',
        ],
        Gatovu: [
          'Cyayi',
          'Gaseke',
          'Gasura',
          'Gitega',
          'Kagunda',
          'Kigarama',
          'Mutarama',
          'Nyabitare',
          'Nyagasambu',
          'Ryamugunga',
        ],
        Kigarama: [
          'Bugagiro',
          'Buremera',
          'Kabusenda',
          'Kagunga',
          'Karugumya',
          'Kigarama',
          'Murama',
          'Nyesonga',
          'Rugara',
          'Rugarama',
        ],
        Kimana: [
          'Akabanga',
          'Kamabuye',
          'Kamutabazi',
          'Kibirizi',
          'Murambi',
          'Nyabiduha',
          'Nyamiyaga',
          'Ramba',
          'Rurama',
          'Rusenyi',
        ],
      },
      Ndora: {
        Bweya: [
          'Akiminazi',
          'Gatobotobo',
          'Kamahembe',
          'Kantabana',
          'Mirayi',
          'Sabudari',
        ],
        Cyamukuza: [
          'Giseke',
          'Nyaburondwe',
          'Nyarubari',
          'Ryabiyaga',
          'Sagahungu',
          'Urusenyi',
        ],
        Dahwe: [
          'Agasharu',
          'Gahondo',
          'Gitwa',
          'Kigarama',
          'Ndatemwa',
          'Twarubona',
        ],
        Gisagara: [
          'Gisagara',
          'Kabuga',
          'Kabuye',
          'Ndora',
          'Nyabitare',
          'Nyamigango',
          'Nyarunazi',
          'Rugara',
          'Rutonde',
        ],
        Mukande: [
          'Bugarama',
          'Kidwange',
          'Nkinda I',
          'Nkinda II',
          'Nyarunyinya',
          'Nyarusange',
        ],
      },
      Nyanza: {
        Higiro: [
          'Agatare',
          'Kabakene',
          'Akagarama',
          'Amashya',
          'Impinga II',
          'Rama',
          'Ruvugizo',
          'Uruvumvuti',
        ],
        Nyamugari: [
          'Akayange',
          'Cyumba',
          'Gatarinzira',
          'Kigali',
          'Rwamiko',
          'Sare',
          'Urugogwe',
          'Urutoyi',
        ],
        Nyaruteja: [
          'Agahehe',
          'Akamerwe',
          'Akasemabondi',
          'Marambya',
          'Gisunzu',
          'Impinga I',
          'Intuntu',
          'Rugayantete',
          'Rugomero',
        ],
        Umubanga: [
          'Akamabuye',
          'Akarwishyura',
          'Akinyana',
          'Maheresho',
          'Manyoni',
          'Remera',
          'Tundiro',
          'Urukeri',
        ],
      },
      Save: {
        Gatoki: [
          'Gasambu',
          'Gashubi',
          'Kampuro',
          'Kaneke',
          'Kavumu',
          'Nyarigina',
          'Rugarama',
        ],
        Munazi: [
          'Kadurumba',
          'Gakombe',
          'Gitwa',
          'Kabitoki',
          'Kigwa',
          'Nyarure',
          'Rwoserezo',
          'Zihare',
        ],
        Rwanza: [
          'Akarambo',
          'Bazenga',
          'Bitabire',
          'Bwinyambo',
          'Cyezuburo',
          'Gahora',
          'Kamudahunga',
          'Kigarama',
          'Kivumu',
          'Nyabitare',
          'Nyagacyamu',
          'Ryamaguri',
        ],
        Shyanda: [
          'Gahora',
          'Kagende',
          'Kirehe',
          'Kirira',
          'Mpinga',
          'Mukoni',
          'Rugori',
          'Ryakabuye',
          'Ryamutabazi',
          'Taba',
        ],
        Zivu: [
          'Kinyonzwe',
          'Musekera',
          'Nyagasozi',
          'Rugogwe',
          'Rwanzana',
          'Ryamurongo',
          'Ryarubayi',
        ],
      },
    },
    Huye: {
      Gishamvu: {
        Nyakibanda: ['Byimana', 'Kamabuye', 'Karambo', 'Kigarama'],
        Nyumba: [
          'Akagahaya',
          'Busoro',
          'Gasyankingi',
          'Gishamvu',
          'Mirambi',
          'Nyagatama',
        ],
        Ryakibogo: [
          'Gakombe',
          'Gasekebuye',
          'Gitwa',
          'Impinga',
          'Kadahokwa',
          'Kidahire',
          'Kiduha',
        ],
        Shori: [
          'Akabere',
          'Cyambwe',
          'Kabeza',
          'Karubare',
          'Kinyovi',
          'Rebero',
          'Rusasa',
          'Umunyinya',
        ],
      },
      Huye: {
        Muyogoro: [
          'Agacyamu',
          'Agasharu',
          'Akagarama',
          'Akaruzi',
          'Kigarama',
          'Munini',
          'Nkamatira',
          'Nyarutovu',
          'Nyarwumba',
          'Rugerero',
          'Rwankoni',
          'Rwaza',
          'Shuni',
        ],
        Nyakagezi: [
          'Gatongati',
          'Kamutima',
          'Karuhinda',
          'Kigarama',
          'Kinyana',
          'Kinyinya',
          'Mbuba',
          'Munanira',
          'Nyarunazi',
          'Rugarama',
        ],
        Rukira: [
          'Agacyamu',
          'Agahenerezo',
          'Agakombe',
          'Agasharu',
          'Gitwa',
          'Kanazi',
          'Kaseramba',
          'Kubutare',
          'Magonde',
          'Nyagasambu',
          'Nyanza',
          'Rugarama',
          'Sabaderi',
        ],
        Sovu: [
          'Gako',
          'Gasongati',
          'Gikombe',
          'Kabagendera',
          'Karambo',
          'Karuhayi',
          'Kigarama',
          'Ngobagoba',
          'Rwezamenyo',
        ],
      },
      Karama: {
        Buhoro: ['Kibingo', 'Mataba', 'Mitsinda', 'Nyamapfunda', 'Nyamikaba'],
        Bunazi: ['Agatenderi', 'Akarehe', 'Ikigarama', 'Kinani', 'Rwezamenyo'],
        Gahororo: [
          'Akarambo',
          'Mavumba',
          'Mukongoro',
          'Nyarusange',
          'Sangano',
          'Umuyange',
          'Uwarugondo',
        ],
        Kibingo: [
          'Agasharu',
          'Agatovu',
          'Mukimba',
          'Nkoto',
          'Nyesonga',
          'Zaga',
        ],
        Muhembe: ['Butare', 'Cyetete', 'Kaburemera', 'Rugege', 'Uwimpundu'],
      },
      Kigoma: {
        Gishihe: [
          'Birambo',
          'Gihanda',
          'Gishihe',
          'Kababaji',
          'Kabingo',
          'Kamyuga',
          'Karambi',
          'Kavumu',
        ],
        Kabatwa: [
          'Bande',
          'Buremera',
          'Kamihuro',
          'Karuhimbana',
          'Kinyata',
          'Mahwa',
          'Mbogo',
          'Sekera',
        ],
        Kabuga: [
          'Kabingo',
          'Kagina',
          'Kanyamugira',
          'Nyarunazi',
          'Ruhungu',
          'Rwabuye',
          'Sanzu',
        ],
        Karambi: [
          'Gasura',
          'Gituntu',
          'Gitwa',
          'Kagarama',
          'Kigarama',
          'Nyarunyinya',
          'Rebo',
        ],
        Musebeya: [
          'Gatovu',
          'Kabacuzi',
          'Kabakobwa',
          'Nyagasozi',
          'Nyarurembo',
          'Rusenyi',
        ],
        Nyabisindu: [
          'Kabugabo',
          'Kabumba',
          'Karambi',
          'Mubuga',
          'Nkenke',
          'Nyanzamura',
          'Rugarama',
          'Shaba',
        ],
        Rugarama: [
          'Birembo',
          'Birinjo',
          'Gasharu',
          'Kabumba',
          'Kakarusho',
          'Kanyurapfundo',
          'Nyagahinga',
          'Ruhinga',
          'Ryaruhimbya',
        ],
        Shanga: [
          'Gasharu',
          'Akaderege',
          'Gaseke',
          'Kabicuki',
          'Ntuntu',
          'Nyamirama',
          'Serugenzi',
        ],
      },
      Kinazi: {
        Byinza: ['Buremera', 'Gakoni', 'Nyarurama', 'Rwerinka'],
        Gahana: ['Cyegera', 'Gasaka', 'Gihana', 'Rugarama', 'Sogwe'],
        Gitovu: [
          'Hanika',
          'Karambo',
          'Kinazi',
          'Muti',
          'Nyarugunga',
          'Nyarusange',
          'Rubona',
          'Ruvugizo',
        ],
        Kabona: ['Kibiraro', 'Mujyejuru', 'Munyu', 'Remera', 'Rwambariro'],
        Sazange: [
          'Butare',
          'Gahondo',
          'Giseke',
          'Kigarama',
          'Mukuzanyana',
          'Nyabisindu',
        ],
      },
      Maraba: {
        Buremera: ['Buremera', 'Gasarabuye', 'Kinazi', 'Nkorwe'],
        Gasumba: ['Gitabure', 'Gitwa', 'Kinombe', 'Taba'],
        Kabuye: ['Gasharu', 'Murama', 'Nyamvumba', 'Nyarusange', 'Rukeri'],
        Kanyinya: ['Bwegera', 'Gikomero', 'Kabirombe', 'Kayeye'],
        Shanga: [
          'Gasororo',
          'Gatyazo',
          'Kabirizi',
          'Mpinga',
          'Nyamiyaga',
          'Nyantende',
          'Rutontwe',
          'Shyinga',
        ],
        Shyembe: [
          'Gisagara',
          'Kagoma',
          'Karambi',
          'Karambo',
          'Kigarama',
          'Kizi',
        ],
      },
      Mbazi: {
        Gatobotobo: [
          'Agasharu',
          'Akanyinya',
          'Bigangara',
          'Kanyaruhinda',
          'Mpinga',
          'Rubona',
          'Rwabuye',
        ],
        Kabuga: [
          'Gakombe',
          'Gasharu',
          'Gicubuka',
          'Mpinga',
          'Ndobogo',
          'Rwezamenyo',
        ],
        Mutunda: [
          'Kagera',
          'Kigusa',
          'Kimuna',
          'Kinyana',
          'Rugarama',
          'Ruryango',
        ],
        Mwulire: ['Bumbogo', 'Cyayove', 'Gitwa', 'Kaburuba', 'Murambi', 'Taba'],
        Rugango: [
          'Gahanga',
          'Kabakono',
          'Kamunyinya',
          'Kanzeyi',
          'Kibiraro',
          'Kigarama',
          'Mpinga',
          'Ngeri',
          'Nyabisindu',
          'Nyamirundi',
        ],
        Rusagara: ['Buhoro', 'Gitwa', 'Kibirizi', 'Cyingoma', 'Ruhuha'],
        Tare: [
          'Cyahafi',
          'Gashikiri',
          'Kagarama',
          'Kavumu',
          'Kigwene',
          'Rupango',
        ],
      },
      Mukura: {
        Bukomeye: [
          'Bweramana',
          'Cyiri',
          'Gahanga',
          'Gasunzwe',
          'Kigarama',
          'Kizenga',
          'Nyagakingi',
          'Sata',
          'Shingangabo',
          'Taba',
        ],
        Buvumu: [
          'Akagarama',
          'Akayenzi',
          'Akogo',
          'Amasanganzira',
          'Kabeza',
          'Akabutora',
          'Mpinga',
          'Nyagasambu',
          'Remera',
          'Rujumbura',
          'Rusenyi',
          'Taba',
        ],
        Icyeru: [
          'Akabuga',
          'Akamahinda',
          'Gakombe',
          'Nyagisenyi',
          'Nyarusambu',
        ],
        'Rango A': [
          'Agakera',
          'Agakombe',
          'Gaseke',
          'Kabahora',
          'Mpaza',
          'Nyamata',
          'Rwinuma',
        ],
      },
      Ngoma: {
        Butare: [
          'Akabuye',
          'Bukinanyana',
          'Buye',
          'Gasoro',
          'Kabutare',
          'Karubanda',
          'Mamba',
          'Busenyi',
          'Taba',
        ],
        Kaburemera: [
          'Gatoki',
          'Kaguhu',
          'Karambi',
          'Nyabubare',
          'Nyagapfizi',
          'Rugarama',
          'Runga',
        ],
        Matyazo: [
          'Gafurwe',
          'Kabeza',
          'Kamucuzi',
          'Nyabitare',
          'Rurenda',
          'Rusisiro',
          'Ruvuzo',
        ],
        Ngoma: [
          'Ngoma V',
          'Ngoma I',
          'Ngoma III',
          'Ngoma IV',
          'Ngoma VI',
          'Ngoma II',
        ],
      },
      Ruhashya: {
        Busheshi: [
          'Kamuhoza',
          'Kibyagira',
          'Nyabijyo',
          'Nyagatovu',
          'Umuyange',
        ],
        Gatovu: ['Dutare', 'Karambo', 'Kigoma', 'Kiyanza', 'Murama'],
        Karama: ['Gakoni', 'Kampogo', 'Nyakigezi', 'Rukubiro', 'Umuyinza'],
        Mara: ['Bwankusi', 'Gashikiri', 'Gitwa', 'Karambo', 'Rwamara'],
        Muhororo: [
          'Agasharu',
          'Kinziramuhindo',
          'Nyakabingo',
          'Shyara',
          'Taba',
        ],
        Rugogwe: ['Agasharu', 'Akanyana', 'Umurambi'],
        Ruhashya: [
          'Igerero',
          'Kigarama',
          'Mbagabaga',
          'Muginga',
          'Rugarama',
          'Rwamabare',
        ],
      },
      Rusatira: {
        Buhimba: [
          'Gasaka',
          'Agasharu',
          'Impinga',
          'Kanyirankuba',
          'Karubona',
          'Kinkanga',
          'Mucunda',
          'Rugarama',
        ],
        Gafumba: ['Kabuga', 'Kigarama', 'Kigari', 'Mubuga', 'Ruvugizo'],
        Kimirehe: [
          'Gakomeye',
          'Kagasa',
          'Kavumu',
          'Kigarama',
          'Ndyome',
          'Nyakabuye',
          'Nyarutovu',
          'Rubanga',
        ],
        Kimuna: [
          'Kamabuye',
          'Kimigo',
          'Murambi',
          'Nyabusunzu',
          'Rushikiri',
          'Rwamuganda',
        ],
        Kiruhura: [
          'Agasharu',
          'Impinga',
          'Nyagasozi',
          'Nyamuko',
          'Nyarucyamu',
          'Nyarugenge',
          'Rubona',
          'Rugarama',
          'Tumba',
          'Umuremera',
        ],
        Mugogwe: ['Gicubuka', 'Kabeza', 'Kibiraro', 'Mubuga', 'Murambi'],
      },
      Rwaniro: {
        Gatwaro: ['Amarongi', 'Gatwaro', 'Nyakabuye', 'Rumana'],
        Kamwambi: ['Gakomeye', 'Kamwambi', 'Karambo', 'Remera', 'Rurembo'],
        Kibiraro: ['Murehe', 'Nyabisindu', 'Nyamivumu', 'Nyarunyinya'],
        Mwendo: ['Birambo', 'Cyarera', 'Murango', 'Rugerero'],
        Nyamabuye: [
          'Bweramana',
          'Kigarama',
          'Munanira',
          'Nyagacyamu',
          'Nyamabuye',
        ],
        Nyaruhombo: [
          'Gasharu',
          'Kibara',
          'Kigarama',
          'Murambi',
          'Mwezi',
          'Nyabujengwe',
          'Rugarama',
        ],
        Shyunga: ['Karama', 'Karugumya', 'Kiboga', 'Kigarama', 'Rugarama'],
      },
      Simbi: {
        Cyendajuru: [
          'Bisambu',
          'Cyendajuru',
          'Kigarama',
          'Matyazo',
          'Rugarama',
          'Ruhinga',
          'Rwatsi',
        ],
        Gisakura: [
          'Bambiro',
          'Gasharu',
          'Kigarama',
          'Kirarambogo',
          'Nyabisindu',
        ],
        Kabusanza: [
          'Bwiza',
          'Gihinga',
          'Kigarama',
          'Maliza',
          'Muranda',
          'Ndago',
          'Ntobwe',
          'Rusuma',
          'Umurera',
        ],
        Mugobore: [
          'Kigarama',
          'Mugobore',
          'Nyagasozi',
          'Nyamirama',
          'Nyamiyaga',
          'Nyarurembo',
          'Rugarama',
          'Ryasebiganza',
        ],
        Nyangazi: [
          'Igonde',
          'Kabakobwa',
          'Kanyiramana',
          'Karebero',
          'Kinyambo',
          'Ngororero',
          'Nyarukurazo',
          'Remera',
          'Shunga',
          'Umuyange',
        ],
      },
      Tumba: {
        Cyarwa: [
          'Agahora',
          'Agasengasenge',
          'Agasharu',
          'Agateme',
          'Icyiri',
          'Kabeza',
          'Kigarama',
          'Mukoni',
          'Taba',
        ],
        Cyimana: ['Abizerwa', 'Akamuhoza', 'Amahoro', 'Ubumwe', 'Ubwiyunge'],
        Gitwa: ['Gasenyi', 'Berwa', 'Nyarurembo', 'Rebero', 'Rimba'],
        Mpare: [
          'Agasharu',
          'Akabuga',
          'Akarugiranka',
          'Kigarama',
          'Musange',
          'Runyinya',
          'Rwanyanza',
        ],
        'Rango B': [
          'Akabeza',
          'Akakanyamanza',
          'Byimana',
          'Impuhwe',
          'Kigarama',
          'Ntangarugero',
          'Urugwiro',
        ],
      },
    },
    Kamonyi: {
      Gacurabwenge: {
        Gihinga: [
          'Kagarama',
          'Kambyeyi',
          'Karama',
          'Nyagasozi',
          'Nyarunyinya',
          'Ryabitana',
        ],
        Gihira: ['Bugaba', 'Kibanza', 'Kidaturwa', 'Migina', 'Nyabitare'],
        Kigembe: [
          'Buhoro',
          'Kabatsi',
          'Kagarama',
          'Mushimba',
          'Nyakabungo',
          'Rugobagoba',
        ],
        Nkingo: [
          'Juru',
          'Kamonyi',
          'Mataba',
          'Nyamiryango',
          'Nyamugari',
          'Rubona',
        ],
      },
      Karama: {
        Bitare: ['Gisanze', 'Kabuga', 'Kajevuba', 'Kinkeri', 'Kokobe'],
        Bunyonga: ['Bunyonga', 'Nyarurembo', 'Nyenyeri', 'Ryagashaza'],
        Muganza: ['Bitagata', 'Gatare', 'Ngoma', 'Nyamitanga', 'Nyaruteja'],
        Nyamirembe: ['Gaji', 'Gasharu', 'Kavumu', 'Kigabiro', 'Nyakizu'],
      },
      Kayenzi: {
        Bugarama: ['Buhurura', 'Munyegera', 'Nyarurama', 'Remera'],
        Cubi: ['Gitwa', 'Kamabuye', 'Ntwari', 'Nyakigezi', 'Rwishywa'],
        Kayonza: ['Kigwene', 'Muza', 'Nyabubare'],
        Kirwa: ['Gasamba', 'Gisizi', 'Gitwa', 'Kigunga', 'Ruheka'],
        Mataba: ['Gasasa', 'Gikurubuye', 'Kabana', 'Nyarubaya', 'Rugoma'],
        Nyamirama: ['Bushara', 'Kibuye', 'Rugaragara'],
      },
      Kayumbu: {
        Busoro: ['Buramba', 'Manyana', 'Nyabuhoro', 'Nyarugenge'],
        Gaseke: ['Gasiza', 'Kigarama', 'Nyarunyinya'],
        Giko: ['Gasharu', 'Mirehe', 'Nyarusange', 'Ryamanywa'],
        Muyange: ['Kaje', 'Kangenzi', 'Murambi', 'Nyarurembo'],
      },
      Mugina: {
        Jenda: ['Kigarama', 'Kiyonza', 'Mataba Nord', 'Munini', 'Nyamurenga'],
        Kabugondo: ['Bihenga', 'Cyeru', 'Mataba Sud', 'Runzenzi'],
        Mbati: ['Kansoro', 'Kigorora', 'Mbati', 'Mikamba', 'Murambi'],
        Mugina: ['Kagasa', 'Kireka', 'Mparo', 'Mugina'],
        Nteko: ['Gishari', 'Kona', 'Ntasi', 'Nyagisozi', 'Rusoro'],
      },
      Musambira: {
        Buhoro: ['Busasamana', 'Gihembe', 'Gihogwe', 'Reramacu'],
        Cyambwe: [
          'Bimomwe',
          'Gacaca',
          'Giheta',
          'Rugarama',
          'Ruvumura',
          'Shaka',
        ],
        Karengera: ['Kamayanja', 'Mbari', 'Nyarusange', 'Nyarutovu', 'Rubanga'],
        Kivumu: [
          'Gahondo',
          'Gitega',
          'Munazi',
          'Nyagisozi',
          'Nyerenga',
          'Wimana',
        ],
        Mpushi: [
          'Gitwiko',
          'Kabere',
          'Kamashashi',
          'Kingoma',
          'Nyarubuye',
          'Nyarurama',
        ],
        Rukambura: ['Bitsibo', 'Ngoma', 'Nkomane', 'Nyamirembe'],
      },
      Ngamba: {
        Kabuga: [
          'Cyimigenge',
          'Fukwe',
          'Musenyi',
          'Nyagasozi',
          'Nyamugari',
          'Raro',
        ],
        Kazirabonde: [
          'Bigobe',
          'Gatare',
          'Gatwa',
          'Kabande',
          'Kajevuba',
          'Munoga',
        ],
        Marembo: ['Gahinga', 'Kabagogo', 'Kigina', 'Nyabitare', 'Rugarama'],
      },
      Nyamiyaga: {
        Bibungo: [
          'Byenene',
          'Karubanda',
          'Murambi',
          'Nkimbiri',
          'Nyamabere',
          'Nyamurasa',
          'Nyamweru',
          'Rwabinagu',
        ],
        Kabashumba: [
          'Bumbogo',
          'Buye',
          'Gacumu',
          'Kigabiro',
          'Mukuyo',
          'Murehe',
          'Nkoto',
          'Ruvugizo',
          'Ruyumba',
          'Umugarama',
        ],
        Kidahwe: [
          'Kiranzi',
          'Kirehe',
          'Magu',
          'Nyamiyaga',
          'Nyarubuye',
          'Rugarama',
          'Rugwiro',
          'Rwezamenyo',
          'Sabununga',
        ],
        Mukinga: [
          'Birembo',
          'Kabeza',
          'Kayenzi',
          'Mbayaya',
          'Nyabubare',
          'Nyamahuru',
          'Nyarugenge',
          'Nyaruhengeri',
          'Wimana',
        ],
        Ngoma: [
          'Buhoro',
          'Gitega',
          'Kabahazi',
          'Kamabuye',
          'Kinanira',
          'Kivugiza',
          'Munyinya',
          'Rwankeke',
        ],
      },
      Nyarubaka: {
        Gitare: [
          'Karora',
          'Kibingo',
          'Mugereke',
          'Nyabitare',
          'Remera',
          'Rwigerero',
        ],
        Kambyeyi: [
          'Kabungo',
          'Kigwene',
          'Kirwa',
          'Nyagihamba',
          'Ruhuha',
          'Ruseke',
        ],
        Kigusa: [
          'Birembo',
          'Gaserege',
          'Kigarama',
          'Kintama',
          'Rugarama',
          'Rwinanka',
        ],
        Nyagishubi: ['Kabere', 'Ngendo', 'Nombe', 'Nyagasozi', 'Tare'],
        Ruyanza: [
          'Buhunga',
          'Gatagara',
          'Gitega',
          'Kanombe',
          'Kavumu',
          'Ngarama',
        ],
      },
      Rugarika: {
        Bihembe: [
          'Gitwa',
          'Kadasaya',
          'Karama',
          'Rubona',
          'Rutovu',
          'Rwabayanga',
        ],
        Kigese: ['Bikamba', 'Kigese', 'Kirega', 'Mibirizi', 'Rugarama'],
        Masaka: ['Masaka', 'Mpungwe', 'Ruramba', 'Rwimondo', 'Taba'],
        Nyarubuye: [
          'Kabarama',
          'Musave',
          'Nzagwa',
          'Remera',
          'Ruhogo',
          'Samuduha',
        ],
        Sheli: [
          'Sheli',
          'Gatovu',
          'Kagangayire',
          'Karehe',
          'Kigarama',
          'Ntebe',
        ],
      },
      Rukoma: {
        Bugoba: ['Bugoba', 'Gatare', 'Kabuga', 'Nyarurama', 'Nyenge'],
        Buguri: [
          'Buguri',
          'Nyabuvomo',
          'Nyagasozi',
          'Nyakabande',
          'Ruzege',
          'Tunza',
        ],
        Gishyeshye: [
          'Gahungeri',
          'Gishyeshye',
          'Murambi',
          'Nyamabuye',
          'Rubare',
        ],
        Murehe: ['Kabagabo', 'Kamuzi', 'Mubuga', 'Rushikiri', 'Uwingando'],
        Mwirute: ['Gafonogo', 'Mwirute', 'Nyarusave', 'Rubuye', 'Rugarama'],
        Remera: [
          'Gisenyi',
          'Kabande',
          'Kanyinya',
          'Kigarama',
          'Mbizi',
          'Remera',
        ],
        Taba: ['Bukokora', 'Karuri', 'Nyarusange', 'Nyirabihanya', 'Taba'],
      },
      Runda: {
        Gihara: [
          'Bikimba',
          'Bimba',
          'Kabasanza',
          'Nyagatare',
          'Rukaragata',
          'Ruyigi',
        ],
        Kabagesera: ['Bwirabo', 'Kabagesera', 'Muhambara', 'Rubuye', 'Rugogwe'],
        Kagina: ['Gasharara', 'Kagina', 'Kamuhoza', 'Kigusa', 'Rugarama'],
        Muganza: ['Kigabiro', 'Musebeya', 'Nyagacyamu', 'Nyaruhoko', 'Rubona'],
        Ruyenzi: ['Kibaya', 'Nyabitare', 'Nyagacaca', 'Rubumba', 'Rugazi'],
      },
    },
    Muhanga: {
      Cyeza: {
        Biringaga: ['Gatare', 'Karama', 'Kuwimana', 'Munini', 'Nyabisindu'],
        Kigarama: [
          'Cyanika',
          'Kajeje',
          'Mataba',
          'Mbirizi',
          'Nyagatovu',
          'Rwinkuba',
        ],
        Kivumu: [
          'Buruba',
          'Busozi',
          'Bwirika',
          'Bwiza',
          'Kamonyi',
          'Musengo',
          'Takwe',
        ],
        Makera: ['Binunga', 'Kanyanza', 'Kigaga', 'Nyagatovu', 'Rwamugoroba'],
        Nyarunyinya: [
          'Bishike',
          'Bucyeye',
          'Buhoro',
          'Gasovu',
          'Gatete',
          'Rusave',
        ],
        Shori: ['Sholi', 'Karehe', 'Kibumba', 'Nyarubuye', 'Rubimba'],
      },
      Kabacuzi: {
        Buramba: ['Gahembe', 'Gahinga', 'Kabayaza', 'Kirambo', 'Musasa'],
        Butare: ['Buyoga', 'Gihinga', 'Karambo', 'Nyirabwayi'],
        Kabuye: ['Kabuga', 'Peru'],
        Kavumu: ['Gasave', 'Gasiza', 'Kabuga', 'Rebero', 'Rukoma'],
        Kibyimba: ['Gasharu', 'Kamiranzogera', 'Kanka', 'Kibaya'],
        Ngarama: ['Kabuga', 'Karambo', 'Mpanga', 'Nzovi'],
        Ngoma: ['Cyambari', 'Gitwa', 'Nkegete', 'Nyarunyinya', 'Peru'],
        Sholi: ['Gakondokondo', 'Gitwa', 'Jandari', 'Kinyoni', 'Mucyamo'],
      },
      Kibangu: {
        Gisharu: [
          'Buhoro',
          'Kirehe',
          'Murandi',
          'Musezero',
          'Remera',
          'Rwesero',
        ],
        Gitega: [
          'Cyuzu',
          'Kaziba',
          'Muhororo',
          'Musambagiro',
          'Musarara',
          'Nkondo',
        ],
        Jurwe: [
          'Bukiro',
          'Kimisange',
          'Murambi',
          'Nzarwa',
          'Rubona',
          'Ruminantege',
        ],
        Mubuga: ['Jarama', 'Matoshya', 'Mubuga', 'Nyarubuye', 'Nyaruvumu'],
        Rubyiniro: ['Butare', 'Gakurwe', 'Mucyamo', 'Mugari', 'Murehe'],
        Ryakanimba: [
          'Kinogi',
          'Musekera',
          'Mushubaguriko',
          'Mwumba',
          'Nyamugari',
        ],
      },
      Kiyumba: {
        Budende: ['Karambi', 'Muduha', 'Musenyi', 'Ruramba'],
        Ndago: ['Mataba', 'Rwezamenyo', 'Sovu'],
        Remera: ['Cyakabiri', 'Kagahina', 'Kagitaba', 'Nyanza', 'Sabusaro'],
        Ruhina: ['Busumba', 'Gatwa', 'Kabimbura', 'Mubuga', 'Nundwe'],
        Rukeri: [
          'Busindi',
          'Kabuga',
          'Matovu',
          'Munini',
          'Musagara',
          'Nyamirambo',
        ],
      },
      Muhanga: {
        Kanyinya: [
          'Gakomeye',
          'Kanyungura',
          'Mataba',
          'Nyabugwiza',
          'Nyamitanga',
        ],
        Nganzo: [
          'Gasenyi',
          'Gitongati',
          'Kabingo',
          'Kagombero',
          'Kamazu',
          'Karama',
          'Kumukenke',
          'Masumo',
        ],
        Nyamirama: [
          'Cyurutare',
          'Gahabwa',
          'Kantonganiye',
          'Namankurwe',
          'Nyiramarangara',
          'Rwabagenzi',
        ],
        Remera: [
          'Gisiza',
          'Kiyoro',
          'Muhanga',
          'Munzereri',
          'Murama',
          'Naganiro',
        ],
        Tyazo: ['Gasaka', 'Gitima', 'Kivomo', 'Nyahinda', 'Ruhuha'],
      },
      Mushishiro: {
        Matyazo: ['Cyarubambire', 'Gataba', 'Gitwa', 'Kabeza', 'Nyagasozi'],
        Munazi: ['Kabadaha', 'Kabare', 'Kiyoro', 'Rwinkindi'],
        Nyagasozi: [
          'Bandora',
          'Gasharu',
          'Gihara',
          'Gisovu',
          'Kanombe',
          'Kibonwa',
        ],
        Rukaragata: ['Bitsibo', 'Hanika', 'Kamurekezi', 'Kivumu', 'Rugerero'],
        Rwasare: ['Bahimba', 'Kanyinya', 'Karucura', 'Rubona'],
        Rwigerero: ['Nyamasheke', 'Nyanza', 'Rwuki', 'Ryaruyange'],
      },
      Nyabinoni: {
        Gashorera: ['Munyinya', 'Muzamuzi', 'Ndaragati', 'Ryakiyange'],
        Masangano: ['Cyanika', 'Murambi', 'Ngaru'],
        Mbuga: ['Gitaba', 'Karengeri', 'Munini', 'Murama', 'Nyarusange'],
        Muvumba: ['Nyamugari', 'Nyamure', 'Nyanza'],
        Nyarusozi: [
          'Gitwa',
          'Kamahoro',
          'Kanombe',
          'Kanyamizo',
          'Mugeni',
          'Rusenge',
        ],
      },
      Nyamabuye: {
        Gahogo: [
          'Gihuma',
          'Kamazuru',
          'Kamugina',
          'Kavumu',
          'Nyarucyamu I',
          'Nyarucyamu II',
          'Nyarucyamu III',
          'Rutenga',
          'Ruvumera',
        ],
        Gifumba: [
          'Gifumba',
          'Gisiza',
          'Kirebe',
          'Rugarama',
          'Rutarabana',
          'Samuduha',
        ],
        Gitarama: [
          'Gatika',
          'Kagitarama',
          'Kavumu',
          'Nyabisindu',
          'Nyarusiza',
          'Nyarutovu',
        ],
        Remera: [
          'Biti',
          'Gasenyi',
          'Gasharu',
          'Kinyenkanda',
          'Kirenge',
          'Munini',
          'Nete',
          'Nyakabingo',
        ],
      },
      Nyarusange: {
        Mbiriri: [
          'Gasave',
          'Gasharu',
          'Gisasa',
          'Karehe',
          'Kintobo',
          'Ntenderi',
          'Nyarushora',
        ],
        Musongati: [
          'Cyiciro',
          'Jabiro',
          'Kagarama',
          'Kamanga',
          'Murambi',
          'Ngororano',
        ],
        Ngaru: ['Gitega', 'Kibirizi', 'Remera', 'Rukamiro'],
        Rusovu: ['Mututu', 'Rukurazo', 'Rwambariro', 'Vugo'],
      },
      Rongi: {
        Gasagara: [
          'Fumbwe',
          'Gasharu',
          'Kidahwe',
          'Murehe',
          'Musenyi',
          'Nyabugombe',
        ],
        Gasharu: [
          'Birehe',
          'Gituza',
          'Kabirizi',
          'Kabuga',
          'Karama',
          'Nyamiyaga',
        ],
        Karambo: ['Gifurwe', 'Gitwa', 'Nyabikenke', 'Nyagasozi', 'Rushenyi'],
        Nyamirambo: [
          'Gisoro',
          'Kabakungu',
          'Karambi',
          'Masizi',
          'Mugwato',
          'Ntarabana',
          'Rugogwe',
          'Rwamure',
        ],
        Ruhango: ['Burerabana', 'Kondo', 'Muyebe', 'Rukoma'],
      },
      Rugendabari: {
        Gasave: [
          'Gakoma',
          'Gasharu',
          'Giturwa',
          'Nyagasozi',
          'Nyakibuye',
          'Nyamatete',
        ],
        Kanyana: ['Gasovu', 'Kabuba', 'Muheta', 'Ntonde'],
        Kibaga: ['Kiduha', 'Mataba', 'Njamena'],
        Mpinga: ['Buganda', 'Gisiza'],
        Nsanga: ['Mpongo', 'Ngando', 'Nyundo', 'Rugwiza', 'Twabumbogo'],
      },
      Shyogwe: {
        Kinini: [
          'Gatare',
          'Kabungo',
          'Kinyami',
          'Musezero',
          'Nyakabingo',
          'Nyakaguhu',
        ],
        Mbare: [
          'Buriza',
          'Muremberi',
          'Nyabisindu',
          'Rubugurizo',
          'Rubuye',
          'Songa',
          'Vunga',
        ],
        Mubuga: [
          'Gakomeye',
          'Gasharu',
          'Kigarama',
          'Mapfundo',
          'Matsinsi',
          'Nyamaganda',
          'Nyarucyamu',
          'Rwamaraba',
        ],
        Ruli: [
          'Gakombe',
          'Kabeza',
          'Karama',
          'Kavumu',
          'Munyinya',
          'Murambi',
          'Nyagacyamu',
          'Ruhina',
        ],
      },
    },
    Nyamagabe: {
      Buruhukiro: {
        Bushigishigi: ['Bushigishigi', 'Giharayumbu', 'Mugote', 'Rusekera'],
        Byimana: ['Bishyiga', 'Buhoro', 'Gakangaga', 'Gihumo', 'Rukeri'],
        Gifurwe: [
          'Bitaba',
          'Gifurwe',
          'Nganzo',
          'Nyamaberi',
          'Ruronzi',
          'Uwankiriye',
        ],
        Kizimyamuriro: [
          'Gikungu',
          'Gishwati',
          'Kagano',
          'Kinaba',
          'Minaga',
          'Mujerenge',
          'Tantamara',
          'Uwinzira',
        ],
        Munini: [
          'Cyinyonza',
          'Gitovu',
          'Magumira',
          'Matsinda',
          'Munini',
          'Rukwandu',
          'Uwinzovu',
        ],
        Rambya: ['Buruhukiro', 'Kibuburo', 'Mpanga', 'Nkamba', 'Ruseke'],
      },
      Cyanika: {
        Gitega: [
          'Butare',
          'Gaseke',
          'Gasharu',
          'Gitega',
          'Kigarama',
          'Miko',
          'Munyereri',
          'Musasa',
          'Rusarasi',
          'Rwingoma',
        ],
        Karama: [
          'Birambo',
          'Karaba',
          'Karama',
          'Mugamba',
          'Munyinya',
          'Nyamisave',
          'Nyanza',
          'Rwamagana',
        ],
        Kiyumba: [
          'Gatare',
          'Gatentwe',
          'Gikomero',
          'Gishike',
          'Kagarama',
          'Kaviri',
          'Nyarucyamu',
        ],
        Ngoma: [
          'Kabarera',
          'Kamuhirwa',
          'Kavumu',
          'Kinga',
          'Murama',
          'Nyamirambo',
        ],
        Nyanza: [
          'Buhiga',
          'Kibingo',
          'Mirama',
          'Mugombwa',
          'Nyabisindu',
          'Rugaragara',
        ],
        Nyanzoga: [
          'Bigazi',
          'Gafuhisha',
          'Kagarama',
          'Karuvenya',
          'Mbeho',
          'Mugari',
          'Nyamirama',
          'Rusenyi',
        ],
      },
      Gasaka: {
        Kigeme: ['Gakoma', 'Gitaba', 'Munombe', 'Nyentanga'],
        Ngiryi: [
          'Karambi',
          'Kibanda',
          'Kitazigurwa',
          'Munyege',
          'Ngiryi',
          'Sumba',
        ],
        Nyabivumu: ['Dusego', 'Gasharu', 'Nyabivumu', 'Raro'],
        Nyamugari: [
          'Kabacuzi',
          'Kabajogo',
          'Karama',
          'Kigarama',
          'Nyamugari',
          'Nyarusange',
        ],
        Nzega: ['Gasaka', 'Gitantu', 'Kadoma', 'Nzega'],
        Remera: ['Gitwa', 'Kabeza', 'Murambi', 'Muriro', 'Nyamifumba'],
      },
      Gatare: {
        Bakopfu: ['Karambo', 'Karumbi', 'Muhingo', 'Twiya'],
        Gatare: ['Gashasha', 'Kiyovu', 'Murembo', 'Rwamakara', 'Uwisuri'],
        Mukongoro: ['Gikungu', 'Kagano', 'Kageyo', 'Nyakabuye', 'Rukereko'],
        Ruganda: [
          'Gasharu',
          'Gituntu',
          'Kamamara',
          'Masangano',
          'Runaba',
          'Rwangambibi',
        ],
        Shyeru: ['Baziro', 'Bimba', 'Kagusa', 'Ruhanga', 'Rushyarara'],
      },
      Kaduha: {
        Kavumu: [
          'Bamba',
          'Biziguro',
          'Gahama',
          'Gataba',
          'Gitega',
          'Joma',
          'Kabuga',
          'Kamonyi',
          'Karehe',
          'Kavumu',
        ],
        Murambi: ['Kasemanyana', 'Kibiraro', 'Nyaruryango', 'Rebero'],
        Musenyi: [
          'Burengo',
          'Gasovu',
          'Gatoki',
          'Kirwa',
          'Munini',
          'Nganzo',
          'Nyakirambi',
          'Ruganda',
        ],
        Nyabisindu: [
          'Gitabage',
          'Kabaziro',
          'Kanyege',
          'Kasemazi',
          'Kirehe',
          'Kivumu',
          'Muduha',
          'Mukongoro',
        ],
        Nyamiyaga: [
          'Cyugaro',
          'Gashiru',
          'Nkomero',
          'Nyakabingo',
          'Ruhuha',
          'Rukeri',
        ],
      },
      Kamegeri: {
        Bwama: ['Gitwa', 'Kamiro', 'Kigarama'],
        Kamegeri: ['Kinyovu', 'Ntaruka', 'Rweru', 'Sovu'],
        Kirehe: ['Gasharu', 'Kigarama', 'Ryanyirataba'],
        Kizi: ['Gakomeye', 'Kagarama', 'Kinyana'],
        Nyarusiza: ['Bande', 'Nyarusange', 'Nyarusiza', 'Rutuna'],
        Rususa: ['Bahina', 'Baro', 'Kigarama', 'Muhembe'],
      },
      Kibirizi: {
        Bugarama: [
          'Kabarera',
          'Kamina',
          'Karandura',
          'Kivumu',
          'Munazi',
          'Nyabusozi',
        ],
        Bugarura: [
          'Kasebuturanyi',
          'Kirwa',
          'Muyange',
          'Nyakibyeyi',
          'Uwinyana',
        ],
        Gashiha: ['Gasharu', 'Muduha', 'Muganza', 'Nyabubare', 'Rukamiro'],
        Karambo: ['Gisoro', 'Gitwa', 'Kavumu', 'Nyamirama', 'Nyirakiraro'],
        Ruhunga: [
          'Cyamashya',
          'Gakoma',
          'Kabuga',
          'Munombe',
          'Nyagishubi',
          'Ruhurura',
        ],
        Uwindekezi: [
          'Birembo',
          'Gatovu',
          'Karumbi',
          'Kigarama',
          'Mugote',
          'Uwamataba',
        ],
      },
      Kibumbwe: {
        Bwenda: ['Munyinya', 'Murambi', 'Murwa', 'Nyagatovu', 'Nyamirama'],
        Gakanka: [
          'Cyeru',
          'Gikomero',
          'Munini',
          'Nkurubuye',
          'Nyarubuye',
          'Rambya',
        ],
        Kibibi: [
          'Gatandaganya',
          'Kabere',
          'Kanyege',
          'Kirwa',
          'Rwezamenyo',
          'Ryingarura',
        ],
        Nyakiza: [
          'Dusenyi',
          'Karambo',
          'Kinyana',
          'Murambi',
          'Nyakizu',
          'Zigati',
        ],
      },
      Kitabi: {
        Kagano: [
          'Bususuruke',
          'Kintobo',
          'Turonzi',
          'Uwabumenyi',
          'Uwarwubatsi',
          'Uwintyabire',
        ],
        Mujuga: [
          'Gahande',
          'Gasasa',
          'Mujuga',
          'Mukaka',
          'Rwufe',
          'Uwanyakanyeri',
          'Uwinka',
        ],
        Mukungu: ['Gahira', 'Gatare', 'Karambi', 'Uwicurangiro', 'Uwurunazi'],
        Shaba: [
          'Bitaba',
          'Gakoko',
          'Muganza',
          'Muyange',
          'Uwakagoro',
          'Uwinka',
        ],
        Uwingugu: [
          'Gisarenda',
          'Kigari',
          'Rubuye',
          'Ruhanga',
          'Uwimisigati',
          'Uwurunazi',
        ],
      },
      Mbazi: {
        Manwari: ['Karambi', 'Kibumba', 'Kigarama', 'Muhororo'],
        Mutiwingoma: ['Gatwa', 'Kabere', 'Kabuga', 'Muduha', 'Nyamirama'],
        Ngambi: ['Gaseke', 'Kabeza', 'Kivomo', 'Maheresho', 'Munanira'],
        Ngara: [
          'Butare',
          'Gasharu',
          'Gisiza',
          'Gituntu',
          'Nyagishumbu',
          'Ruseke',
        ],
      },
      Mugano: {
        Gitondorero: ['Gakomeye', 'Gitondorero', 'Gituntu', 'Karambi', 'Maso'],
        Gitwa: [
          'Kabuhoro',
          'Kirenzi I',
          'Kirenzi II',
          'Nyakibingo',
          'Rutabo',
          'Ryamigabo',
        ],
        Ruhinga: [
          'Cyibande',
          'Gitarama',
          'Kabuye',
          'Karambi',
          'Kinzira',
          'Runyinya',
        ],
        Sovu: [
          'Kigarama',
          'Nziranziza',
          'Rugarama I',
          'Rugarama II',
          'Ruhanga',
        ],
        Suti: ['Cyabute', 'Gasiza', 'Matyazo', 'Rwamiko', 'Turyango'],
        Yonde: [
          'Gisovu',
          'Kanyegenyege',
          'Nyarusazi',
          'Ruhamira I',
          'Ruhamira II',
        ],
      },
      Musange: {
        Gasave: ['Gasura', 'Kabingo', 'Murambi', 'Nyabivumu', 'Nyakabuye'],
        Jenda: [
          'Cyabagomba',
          'Kabakannyi',
          'Kavumu',
          'Kayogoro',
          'Nyakibungo',
          'Nyakirambi',
        ],
        Masagara: [
          'Cyabasana',
          'Cyaruvunge',
          'Gituntu',
          'Muhororo',
          'Mutakara',
          'Mutuntu',
          'Nyagihima',
        ],
        Masangano: ['Gasagara', 'Kibumba', 'Mubuga', 'Nyakabuye', 'Rutuntu'],
        Masizi: ['Karama', 'Munini', 'Murehe', 'Rwankango', 'Rwina'],
        Nyagisozi: ['Dusenyi', 'Kibaga', 'Remera', 'Ruhuga', 'Uwabarashi'],
      },
      Musebeya: {
        Gatovu: [
          'Bisereganya',
          'Gatovu',
          'Gitovu',
          'Kanyiranzoga',
          'Nyarubande',
          'Ryanyakayaga',
        ],
        Nyarurambi: [
          'Cyabwimba',
          'Cyarwa',
          'Gatiti',
          'Giheta',
          'Kabere',
          'Mujyejuru',
          'Nyarurambi',
          'Rwabigeyo',
        ],
        Rugano: [
          'Bugarama',
          'Busanza',
          'Gisiza',
          'Kibandirwa',
          'Rugano',
          'Rukungu',
        ],
        Runege: [
          'Bigugu',
          'Bitaba',
          'Gacundura',
          'Gakereko',
          'Ndogondwe',
          'Ruganza',
          'Rukaranka',
        ],
        Rusekera: ['Karambo', 'Ngoma', 'Rebero', 'Shaki', 'Uwimituza'],
        Sekera: [
          'Masinde',
          'Mugano',
          'Nkomero',
          'Nyaruhura',
          'Rubumburi',
          'Rugazi',
        ],
      },
      Mushubi: {
        Buteteri: [
          'Gorwe',
          'Kagorwe',
          'Kizanganya',
          'Mugunda',
          'Murambi',
          'Ngoma',
          'Nyakibande',
          'Remera',
          'Rusoyo',
          'Rwamiko',
        ],
        Cyobe: [
          'Cyobe',
          'Gaseke',
          'Gitikirema',
          'Nyagisumo',
          'Nyakabingo',
          'Nyakirambi',
          'Nyarushike',
          'Rutoyi',
        ],
        Gashwati: [
          'Bweramana',
          'Gashwati',
          'Muhembe',
          'Muko',
          'Mushubi',
          'Rucunda',
          'Ruhinga',
        ],
      },
      Nkomane: {
        Bitandara: ['Bitandara', 'Buhanzi', 'Munanira', 'Muyange', 'Rugeyo'],
        Musaraba: [
          'Gatorove',
          'Gihunga',
          'Kimbogo',
          'Musaraba',
          'Rusoyo',
          'Rutare',
          'Rwimpiri',
        ],
        Mutengeri: [
          'Cyurwufe',
          'Gihwahwa',
          'Kavumu',
          'Kivumu',
          'Mutengeri',
          'Tubuye',
        ],
        Nkomane: ['Banda', 'Kagano', 'Mugari', 'Mutarama', 'Ruhinga'],
        Nyarwungo: [
          'Bisharara',
          'Bucyero',
          'Marambo',
          'Nyaruhombo',
          'Nyarwungo',
          'Rangi',
          'Rutoyi',
        ],
        Twiya: ['Gakomeye', 'Gishenge', 'Karukoma', 'Kibuga', 'Twiya'],
      },
      Tare: {
        Buhoro: [
          'Gisanze',
          'Gitovu',
          'Kanserege',
          'Kirwa',
          'Nyabwoma',
          'Rwufe',
          'Ryarubondo',
        ],
        Gasarenda: [
          'Kagarama',
          'Kiminazi',
          'Kivuruga',
          'Murangara',
          'Muse',
          'Mwufe',
          'Uwinkomo',
        ],
        Gatovu: ['Gasenge', 'Kigusa', 'Kimina', 'Muhati', 'Ruziba'],
        Kaganza: [
          'Akanyirandori',
          'Bivumu',
          'Buremera',
          'Cyimicanga',
          'Ruganza',
        ],
        Nkumbure: [
          'Biraro',
          'Bireka',
          'Gahembe',
          'Kibwije',
          'Mubezi',
          'Muhumo',
          'Rugeti',
          'Rukereko',
          'Uwumugeti',
          'Vumwe',
        ],
        Nyamigina: [
          'Gakoma',
          'Maryohe',
          'Ngororero',
          'Nkomero',
          'Nyarugeti',
          'Rukoko',
          'Uwinyana',
        ],
      },
      Uwinkingi: {
        Bigumira: ['Bigumira', 'Cyumuganza', 'Gakoko', 'Magumira'],
        Gahira: [
          'Bunyunyu',
          'Gahira',
          'Gititi',
          'Kibugazi',
          'Kunyu',
          'Rugeyo',
          'Uwinkingi',
        ],
        Kibyagira: [
          'Bishya',
          'Cyumuganza',
          'Kabuga',
          'Kabusekuru',
          'Kagano',
          'Sabake',
          'Sekera',
        ],
        Mudasomwa: ['Gicaca', 'Karambo', 'Nsinduka', 'Rushubi', 'Uwanjyogoro'],
        Munyege: [
          'Bitaba',
          'Gahango',
          'Kanyampongo',
          'Kimina',
          'Munyege',
          'Nyarurambi',
        ],
        Rugogwe: [
          'Mabende',
          'Munini',
          'Mwishogwe',
          'Nyamugari',
          'Rugeti',
          'Subukiniro',
        ],
      },
    },
    Nyanza: {
      Busasamana: {
        Gahondo: [
          'Bigega',
          'Bugura',
          'Kamatovu',
          'Karama',
          'Kavumu',
          'Kibaga',
          'Kiberinka',
          'Nyakwibereka',
          'Nyarutovu',
        ],
        Kavumu: [
          'Akirabo',
          'Gihisi A',
          'Gihisi B',
          'Karukoranya A',
          'Karukoranya B',
          'Majyambere',
          'Mugandamure A',
          'Mugandamure B',
          'Mukoni',
          'Nyagatovu',
          'Nyamagana B',
          'Rukandiro',
          'Ruvumera',
          'Kavumu',
          'Nyamagana A',
        ],
        Kibinja: [
          'Kabuzuru',
          'Kigarama',
          'Mukindo',
          'Ngorongari',
          'Rebero',
          'Rugarama',
          'Rugari A',
          'Rugari B',
        ],
        Nyanza: [
          'Bunyeshywa',
          'Gakenyeri A',
          'Gakenyeri B',
          'Gatare',
          'Gatsinsino',
          'Gatunguru',
          'Gishike',
          'Kavumu',
          'Kigarama',
          'Kivumu',
          'Mugonzi',
          'Nyanza',
          'Nyarunyinya',
          'Rubona',
        ],
        Rwesero: [
          'Bukinankwavu',
          'Gahanda',
          'Gisando',
          'Kabona',
          'Kidaturwa',
          'Murambi',
          'Mwima',
          'Nyabisindu',
          'Rugarama',
          'Rukari',
          'Rwesero',
          'Taba',
        ],
      },
      Busoro: {
        Gitovu: [
          'Gitega',
          'Kabeza',
          'Kayenzi',
          'Muhindo',
          'Musumba',
          'Nazareti',
          'Nyacyonga',
          'Nyagasambu',
          'Rushoka',
        ],
        Kimirama: [
          'Gitwa',
          'Kimirama',
          'Kireranyana',
          'Ndamira',
          'Nyamiyonga',
          'Nyarugenge',
          'Rugarama',
        ],
        Masangano: [
          'Busoro',
          'Bweramana',
          'Gikombe',
          'Masangano',
          'Murambi',
          'Nyarugunga',
          'Runyonza',
          'Shinga',
        ],
        Munyinya: ['Kagarama', 'Karambi', 'Kigali', 'Kivugiza', 'Rwara'],
        Rukingiro: [
          'Cyamugani',
          'Cyuriro',
          'Gasambu',
          'Runazi',
          'Rwanamiza',
          'Rwangoga',
        ],
        Shyira: [
          'Gahogo',
          'Kinkanga',
          'Nyamoyaga',
          'Rucyamo',
          'Rusharu',
          'Saruduha',
        ],
      },
      Cyabakamyi: {
        Kadaho: [
          'Gahengeri',
          'Gasenyi',
          'Gataba',
          'Gitega',
          'Kabere',
          'Kabeza',
          'Kadaho',
          'Nyabisazi',
          'Nyabyiyoni',
        ],
        Karama: [
          'Butembo',
          'Cyarera',
          'Gahondo',
          'Gatongati',
          'Kamabuye',
          'Kamonyi',
          'Karama',
          'Nyabinombe',
        ],
        Nyabinyenga: [
          'Kabuga',
          'Kandihe',
          'Karehe',
          'Kimiyumbu',
          'Nyabinyenga',
          'Rugwa',
          'Rwamagana',
          'Taba',
        ],
        Nyarurama: [
          'Kabyuma',
          'Kigarama',
          'Kirombozi',
          'Nyakabingo',
          'Rugote',
          'Ruvuzo',
          'Rwabatwa',
          'Rwamiko',
        ],
        Rubona: [
          'Bikombe',
          'Bugarama',
          'Gahunga',
          'Karambo',
          'Kavumu',
          'Murambi',
          'Nyabishike',
          'Nyaminazi',
          'Nyarutovu',
          'Rugendabari',
        ],
      },
      Kibilizi: {
        Cyeru: [
          'Gasagara',
          'Gisika',
          'Kamatamu',
          'Karama',
          'Matara',
          'Muyebe',
          'Nyamunini',
          'Rutete',
        ],
        Mbuye: [
          'Binyana',
          'Gako',
          'Gihama',
          'Karambi',
          'Karehe',
          'Kigarama',
          'Mukoni',
          'Rukore',
        ],
        Mututu: [
          'Gatongati',
          'Gicumbi',
          'Kabeza',
          'Kanyinya',
          'Kivugiza',
          'Masangano',
        ],
        Rwotso: [
          'Bigarama',
          'Kabuga',
          'Kibilizi',
          'Mubano',
          'Mubuga',
          'Mutima',
          'Nyarurama',
          'Runyonza',
          'Rusagara',
          'Saruhembe',
        ],
      },
      Kigoma: {
        Butansinda: [
          'Butatsinda',
          'Gitare',
          'Shusho',
          'Karama',
          'Karambo',
          'Kayange',
          'Kibaza',
          'Kigoma',
          'Marongi',
          'Mataba',
          'Nyesonga',
        ],
        Butara: [
          'Buruba',
          'Butara',
          'Gasharu',
          'Kavumu',
          'Kigufi',
          'Kirundo',
          'Nyabusheshe',
          'Runyinya',
        ],
        Gahombo: [
          'Birembo',
          'Cyingina',
          'Gashikiri',
          'Gicunshu',
          'Gisore',
          'Karugando',
          'Kaziba',
          'Kirerabana',
          'Nyagacyamo',
          'Rugarama',
          'Serivise',
        ],
        Gasoro: [
          'Bugarura',
          'Bwambika',
          'Gisoro',
          'Giturwa',
          'Kabacuzi',
          'Kajevuba',
          'Kinene',
          'Mutende',
          'Nyabubare',
          'Nyakabungo',
          'Runyanzige',
          'Sholi',
        ],
        Mulinja: [
          'Akana Ka Mulinja',
          'Akintare',
          'Buharankakara',
          'Buhoro',
          'Burambi',
          'Karama',
          'Kigarama',
          'Muramba',
          'Nyarukurazo',
          'Sabununga',
        ],
      },
      Mukingo: {
        Cyerezo: [
          'Birambo',
          'Bweramana',
          'Cyerezo',
          'Cyikirehe',
          'Cyumba',
          'Gasharu',
          'Kamabuye',
          'Karambi',
          'Nyarutovu',
        ],
        Gatagara: [
          'Cyahafi',
          'Gatagara',
          'Kamushatsi',
          'Karama',
          'Karuhwanya',
          'Kinyogoto',
          'Muhororo',
          'Nyamiyaga',
          'Nyamuko',
        ],
        Kiruli: [
          'Gahoko',
          'Kaganza',
          'Kiganda',
          'Kigarama',
          'Masambu',
          'Muganza',
          'Murehe',
          'Muturirwa',
          'Nkiko',
          'Nyabishinge',
          'Nyankunamirwa',
        ],
        Mpanga: [
          'Birembo',
          'Karambi',
          'Kinyinya',
          'Mataba',
          'Nkinda',
          'Nyakabuye',
          'Nyamazi',
          'Remera',
        ],
        Ngwa: [
          'Bikire',
          'Biroro',
          'Gasiza',
          'Kagwa A',
          'Karambi A',
          'Karenge',
          'Kidaturwa',
          'Kigarama',
          'Mwanabiri',
          'Nyarunyinya A',
          'Rutete',
        ],
        Nkomero: [
          'Cyimana',
          'Gisuma',
          'Kabarima',
          'Kibonde',
          'Kigarama',
          'Nyacyoma',
          'Nyakabungo',
          'Nyankokoma',
          'Nzuki',
          'Ruhosha',
        ],
      },
      Muyira: {
        Gati: ['Buhaza', 'Kimfizi', 'Kinyoni', 'Ruyenzi', 'Rwabihanga'],
        Migina: ['Bugina', 'Kalilisi', 'Kavumu', 'Kinyana', 'Musenyi'],
        Nyamiyaga: ['Gihama', 'Kabuye', 'Kiniga', 'Nzovi', 'Rugese'],
        Nyamure: ['Cyegera', 'Gatare', 'Gituza', 'Kanyundo', 'Nyarugunga'],
        Nyundo: ['Jari', 'Nyundo', 'Mugari', 'Muyira', 'Nzoga'],
      },
      Ntyazo: {
        Bugali: [
          'Gakindo',
          'Gisayura',
          'Kabusheja',
          'Kiruhura',
          'Marabage',
          'Ndago',
          'Nkomane',
          'Nyabitare',
          'Rugarama',
        ],
        Cyotamakara: [
          'Bayi',
          'Kankima',
          'Karuyumbo',
          'Misasa',
          'Mpande',
          'Nyabigugu',
          'Nyarutovu',
          'Ruyenzi',
          'Rwimpundu',
        ],
        Kagunga: [
          'Bukinanyana',
          'Kamabuye',
          'Kimigunga',
          'Ntebe',
          'Nyakabungo',
          'Nyamirama',
          'Nyamirambo',
          'Nyamizi',
          'Nyarubuye',
          'Rusasa',
          'Samuduha',
        ],
        Katarara: [
          'Gasharu',
          'Kagarama',
          'Kamabuye',
          'Muhero',
          'Munyiginya',
          'Muyenzi',
          'Nkombe',
          'Rebero',
          'Rukoma',
          'Rusebeya',
        ],
      },
      Nyagisozi: {
        Gahunga: [
          'Gatare',
          'Gihara',
          'Gituntu',
          'Kagarama',
          'Kigohe',
          'Mweya',
          'Nyamugari',
          'Uwarukara',
        ],
        Kabirizi: [
          'Cyahafi',
          'Gihimbi',
          'Kabuye',
          'Muhaga',
          'Nyagatovu',
          'Nyamabuye',
          'Nyaruvumu',
        ],
        Kabuga: [
          'Gatoki',
          'Mirehe',
          'Murandaryi',
          'Mwokora',
          'Nyamitobo',
          'Uwabushingwe',
          'Uwagisozi',
          'Uwimpura',
        ],
        Kirambi: [
          'Busenyeye',
          'Bweru',
          'Gasharu',
          'Gasiza',
          'Jarama',
          'Mpaza',
          'Murende',
          'Mwezi',
          'Rwankuba',
          'Rwimbazi',
        ],
        Rurangazi: [
          'Gashyenzi',
          'Kami',
          'Kigarama',
          'Musongati',
          'Nyamagana',
          'Nyarutovu',
          'Nyaruvumu',
          'Rugarama',
        ],
      },
      Rwabicuma: {
        Gacu: ['Bisambu', 'Gisake', 'Karehe', 'Nyamiyaga'],
        Gishike: [
          'Gakoni',
          'Gasiza A',
          'Gasiza B',
          'Karambo A',
          'Karambo B',
          'Karusimbi',
          'Rwamushumba',
        ],
        Mubuga: ['Kabisine', 'Kadusenyi', 'Karwiru', 'Nyamiseke'],
        Mushirarungu: ['Kirwa', 'Nyabubare', 'Nyamivumu A', 'Nyamuvumu B'],
        Nyarusange: [
          'Cyarwa',
          'Kamushi',
          'Kamuvunyi A',
          'Kamuvunyi B',
          'Karambi',
          'Kavumu A',
          'Kavumu B',
        ],
        Runga: ['Kigarama', 'Murambi', 'Ndago', 'Rugarama A', 'Rugarama B'],
      },
    },
    Nyaruguru: {
      Busanze: {
        Kirarangombe: [
          'Bukinanyana',
          'Gisenyi',
          'Gitwe',
          'Kinyinya',
          'Masiga',
          'Uwindava',
        ],
        Nkanda: ['Bitare', 'Mutarama', 'Mutobo', 'Nkanda', 'Uwamakumba'],
        Nteko: [
          'Gisoro',
          'Kabavomo',
          'Ndatemwa',
          'Nteko',
          'Nyarukeri',
          'Nyarusange',
        ],
        Runyombyi: [
          'Bugina',
          'Gabiro',
          'Musebeya',
          'Rango',
          'Ryabusagara',
          'Shwima',
        ],
        Shororo: [
          'Bukinga',
          'Mirindi',
          'Murambi',
          'Runyami',
          'Rutabo',
          'Uwinteko',
        ],
      },
      Cyahinda: {
        Coko: ['Agasharu', 'Coko', 'Gitara', 'Ruko'],
        Cyahinda: ['Cyahinda', 'Cyanwa', 'Kinyaga', 'Saburunduru', 'Rutega'],
        Gasasa: ['Gasasa', 'Kavumu', 'Mugari', 'Ryamarembo'],
        Muhambara: [
          'Busanza',
          'Byanone',
          'Gasharu',
          'Kubitiro',
          'Nyagatovu',
          'Rebero',
        ],
        Rutobwe: [
          'Kanyinya',
          'Kibumba',
          'Ngobyi',
          'Rubona',
          'Rugarama',
          'Rutobwe',
        ],
      },
      Kibeho: {
        Gakoma: ['Nyagishayo', 'Rurembo', 'Viro'],
        Kibeho: ['Agateko', 'Akajonge', 'Sinayi'],
        Mbasa: ['Kinazi', 'Migina', 'Rwimbogo'],
        Mpanda: ['Banga', 'Kibayi', 'Mpanda', 'Munege'],
        Mubuga: ['Mubuga', 'Nyarusovu', 'Nyarwumba', 'Umurambi', 'Uwintobo'],
        Nyange: ['Agateko', 'Kigona', 'Mpatswe', 'Nkomero'],
      },
      Kivu: {
        Cyanyirankora: ['Businde', 'Cyanyirankora', 'Gakuta', 'Ruganza'],
        Gahurizo: ['Gasezo', 'Kintama', 'Kintare', 'Uwamizirikano'],
        Kimina: ['Kabeza', 'Kabingo', 'Kimina', 'Uwisaga'],
        Kivu: ['Kavumu', 'Kivu', 'Murambi', 'Rubumburi', 'Rusuzumiro'],
        Rugerero: ['Kivumu', 'Misundwe', 'Nyarwotsi', 'Rugerero'],
      },
      Mata: {
        Gorwe: ['Mataba', 'Rimbanya', 'Ruhunga'],
        Murambi: ['Mata', 'Murambi', 'Nyamyumba', 'Runono'],
        Nyamabuye: ['Nyacyondo', 'Rwinanka', 'Tububuru'],
        Ramba: ['Cyafurwe', 'Gasasa', 'Ramba'],
        Rwamiko: ['Matyazo', 'Rwamiko', 'Taba'],
      },
      Muganza: {
        Muganza: [
          'Gashinge',
          'Mubazi',
          'Muganza',
          'Ngara',
          'Nyabirondo',
          'Rambyanyana',
        ],
        Rukore: [
          'Kanazi',
          'Karanka',
          'Nyagisenyi',
          'Remera',
          'Rwishywa',
          'Uwinzira',
        ],
        Samiyonga: [
          'Bigugu',
          'Cyurukore',
          'Gituntu',
          'Kigwene',
          'Mazimeru',
          'Murambi',
          'Tangabo',
        ],
        Uwacyiza: [
          'Bitaba',
          'Migendo',
          'Mukongoro',
          'Murambya',
          'Mutovu',
          'Sekera',
        ],
      },
      Munini: {
        Giheta: ['Gacumu', 'Gahango', 'Gasare', 'Giheta', 'Mashya'],
        Ngarurira: ['Agatare', 'Akarehe', 'Gisizi', 'Gitega', 'Uwumuko'],
        Ngeri: ['Akagera', 'Mushwati', 'Ndago', 'Rubona', 'Ruseke', 'Rushubi'],
        Ntwali: ['Kabirizi', 'Ntwari', 'Nyambaragasa', 'Rwinanka', 'Umurambi'],
        Nyarure: [
          'Kamana',
          'Kimena',
          'Muhororo',
          'Munanira',
          'Nyarure',
          'Sheke',
        ],
      },
      Ngera: {
        Bitare: ['Bitare', 'Gashiru', 'Sheke'],
        Mukuge: ['Cyamutumba', 'Cyaratsi', 'Mukuge'],
        Murama: ['Kaganda', 'Mbogo', 'Nyarugano', 'Runyami'],
        Nyamirama: ['Kinteko', 'Mubuga', 'Nyamirama'],
        Nyanza: ['Gisozi', 'Kibingo', 'Mpinga', 'Nyanza'],
        Yaramba: ['Buhunga', 'Kirwa', 'Musumba', 'Yaramba'],
      },
      Ngoma: {
        Fugi: ['Akanyaru', 'Gasha', 'Mutakwa', 'Nteko', 'Ruli', 'Urugeyo'],
        Kibangu: ['Gituramigina', 'Kirehe', 'Kiriro', 'Nyarukeri'],
        Kiyonza: [
          'Akagano',
          'Gacumbi',
          'Maraba',
          'Munini',
          'Mwumba',
          'Nyagahinga',
        ],
        Mbuye: ['Gihishabwenge', 'Kigarama', 'Mugobe', 'Mujahu', 'Ururambo'],
        Nyamirama: [
          'Akabuye',
          'Bihembe',
          'Nyagasozi',
          'Rushubi',
          'Ryakanyamiganda',
        ],
        Rubona: [
          'Agasaka',
          'Agatovu',
          'Akarambo',
          'Nyamirama',
          'Ryarugarama',
          'Shyoko',
        ],
      },
      Nyabimata: {
        Gihemvu: ['Bihembe', 'Bugina', 'Gihemvu', 'Rugarama'],
        Kabere: ['Kabere', 'Nyarunazi', 'Uwurusugi'],
        Mishungero: ['Mishungero', 'Muyira', 'Ngarama', 'Rubindi', 'Uwaruhigi'],
        Nyabimata: ['Murambi', 'Mutobwe', 'Nyabimata', 'Rwerere'],
        Ruhinga: ['Agasugi', 'Cyumuzi', 'Ndaro', 'Ruhinga'],
      },
      Nyagisozi: {
        Maraba: ['Bugarama', 'Maraba', 'Nkima', 'Rushunguriro'],
        Mwoya: [
          'Agatovu',
          'Bwerankori',
          'Muhombo',
          'Mwoya',
          'Nkomero',
          'Nyagashubi',
        ],
        Nkakwa: [
          'Bihembe',
          'Kaduha',
          'Nkakwa',
          'Nyarubuye',
          'Rarire',
          'Rubuga',
        ],
        Nyagisozi: [
          'Muriza',
          'Nyagishayo',
          'Nyamiyaga',
          'Ryabidandi',
          'Uwimfizi',
        ],
      },
      Ruheru: {
        Gitita: [
          'Gahotora',
          'Kibyibushye',
          'Nyacyonga',
          'Ruganza',
          'Rusagara',
          'Ryanyaruja',
        ],
        Kabere: [
          'Busenyi',
          'Gambiriro',
          'Mukaka',
          'Murambi',
          'Nshenyi',
          'Uwigisura',
        ],
        Remera: ['Cyivugiza', 'Gitwa', 'Kirwa', 'Mutumba', 'Uwinyana'],
        Ruyenzi: ['Rukarakara', 'Ruvuru', 'Ruyenzi', 'Tambananga', 'Zirambi'],
        Uwumusebeya: ['Gakaranka', 'Mubuga', 'Rugote', 'Uwimbogo', 'Yanza'],
      },
      Ruramba: {
        Gabiro: ['Bukoro', 'Kageyo', 'Kansi', 'Nyamirambo', 'Ryamuhumbi'],
        Giseke: ['Giseke', 'Kabari', 'Kidogo', 'Matyazo', 'Tugogo'],
        Nyarugano: ['Gisorora', 'Kinyonyo', 'Nyarugano', 'Uruyange'],
        Rugogwe: ['Rugogwe', 'Rugusa', 'Titi'],
        Ruramba: ['Bugizi', 'Busasamana', 'Karambi', 'Ruramba'],
      },
      Rusenge: {
        Bunge: ['Bunge', 'Jali', 'Nyanzoga', 'Toraniro'],
        Cyuna: ['Cyuna', 'Kiramutse', 'Remera', 'Uwamuhizi'],
        Gikunzi: ['Jali', 'Kibu', 'Munanira', 'Rwabujagi'],
        Mariba: ['Gihango', 'Kabuye', 'Miko', 'Rasaniro'],
        Raranzige: ['Akabacura', 'Gasave', 'Karimba', 'Ntanda', 'Nyamugari'],
        Rusenge: ['Kabacuzi', 'Kamusindi', 'Kavumu', 'Runyinya'],
      },
    },
    Ruhango: {
      Bweramana: {
        Buhanda: [
          'Bugufi',
          'Gakongoro',
          'Gikarabiro',
          'Kabere',
          'Kamatungo',
          'Kavumu',
          'Mpunu',
          'Munini',
          'Nyakidahe',
          'Nyarubuye',
          'Rutarabana',
        ],
        Gitisi: [
          'Kabugusu',
          'Nyamaraba',
          'Nyarugenge',
          'Nyarunyinya',
          'Ruvugizo',
        ],
        Murama: [
          'Duwane',
          'Gasharu',
          'Gisagara',
          'Kamirishyo',
          'Karambo',
          'Karima',
          'Karutsindo',
          'Kigarama',
          'Kivomo',
          'Rusororo',
          'Rwavuningoma',
          'Rwingwe',
        ],
        Rubona: [
          'Birambo',
          'Bugari',
          'Gasharu',
          'Kabega',
          'Kirambo',
          'Masambu',
          'Mataba',
          'Munyinya',
          'Ntosho',
          'Nyagasozi',
          'Nyakabanda',
          'Nyamuko',
          'Rugogwe',
        ],
        Rwinyana: [
          'Karambi',
          'Kumunyinya',
          'Mubuga',
          'Mukingi',
          'Nyagakombe',
          'Nyagitongwe',
          'Nyarubuye',
          'Nyarutovu',
          'Rugarama',
          'Rugogwe',
          'Rwinyana',
          'Samba',
        ],
      },
      Byimana: {
        Kamusenyi: [
          'Gahama',
          'Gakomeye',
          'Gakurazo',
          'Gasharu',
          'Gasiza',
          'Gitanga',
          'Kabusheshe',
          'Kinama',
          'Mayebe',
          'Nyakabungo',
          'Nyarusange',
          'Rugerero',
        ],
        Kirengeri: [
          'Gahengeri',
          'Gatoki',
          'Kamonyi',
          'Kirengeri',
          'Masaka',
          'Nyabizenga',
          'Nyamirambo',
          'Rusororo',
        ],
        Mahembe: [
          'Akabere',
          'Kavumu',
          'Muhororo',
          'Mujyejuru',
          'Mutobo',
          'Nyabisindu',
          'Nyagisozi',
        ],
        Mpanda: [
          'Bisika',
          'Gatwa',
          'Gitega',
          'Kanyarira',
          'Karenge',
          'Kibande',
          'Mpanda',
          'Nyaburondwe',
          'Nyagahinga',
        ],
        Muhororo: [
          'Bukomero',
          'Karama',
          'Karenge',
          'Kigarama',
          'Mbuye',
          'Nyamiseke',
          'Nyarunyinya',
          'Remera',
          'Rukuro',
          'Rutembo',
        ],
        Ntenyo: [
          'Bugarura',
          'Gihinga',
          'Kageyo',
          'Kamurenzi',
          'Kavumu',
          'Mucubi',
          'Ngando',
          'Ntenyo',
          'Nyabisindu',
          'Rukiriza',
        ],
        Nyakabuye: [
          'Gasasa',
          'Gatobotobo',
          'Kizibaziba',
          'Muhororo',
          'Ndago',
          'Nyarubumbiro',
          'Nyarutovu',
        ],
      },
      Kabagali: {
        Bihembe: [
          'Bihembe',
          'Bwama',
          'Kanyinya',
          'Kirwa',
          'Misambagiro',
          'Nyagatovu',
          'Rusisiro',
        ],
        Karambi: [
          'Bugaramantare',
          'Karambi',
          'Karurara',
          'Kashyamba',
          'Mbuye',
          'Muhoza',
          'Rambyanyana',
        ],
        Munanira: [
          'Byimana',
          'Kagitare',
          'Kavumu',
          'Munanira',
          'Muremera',
          'Musekera',
          'Nyabyunyu',
          'Remera',
          'Ruyogoro',
        ],
        Remera: [
          'Birambo',
          'Kabacuzi',
          'Kamuhirwa',
          'Muhororo',
          'Nyarusange',
          'Ruhare',
          'Rwankuba',
        ],
        Rwesero: [
          'Bugaramantare',
          'Mayebe',
          'Nyabivumu',
          'Remera',
          'Rwesero',
          'Serugeme',
        ],
        Rwoga: [
          'Cyunyu',
          'Gasharu',
          'Gitwa',
          'Kabakamba',
          'Kanyinya',
          'Kavumu',
          'Kiyanja',
          'Nyabitare',
          'Nyagisenyi',
          'Nyarushishi',
          'Rusebeya',
        ],
      },
      Kinazi: {
        Burima: [
          'Burima',
          'Mirambi',
          'Nyagahama',
          'Nyamiyaga',
          'Nyarugenge',
          'Nyaruteja',
        ],
        Gisali: [
          'Gisari',
          'Kabeza',
          'Kaduha',
          'Kakirenzi',
          'Kamuraza',
          'Kanaba',
          'Kibanda',
          'Matara',
          'Nyabusunzu',
          'Nyiranduga',
          'Remera',
        ],
        Kinazi: [
          'Gasiza',
          'Impara',
          'Kabuga',
          'Kacyiru',
          'Kamabuye',
          'Karama',
          'Kareshya',
          'Karuhuga',
          'Marche -commun',
          'Mpemba',
          'Nyabinyenga',
          'Nyabisindu',
          'Nyiraruhinga',
          'Rebero',
          'Ruhuha',
        ],
        Rubona: [
          'Buhanika',
          'Gafumba',
          'Gako',
          'Gashike',
          'Kagazi',
          'Kigarama',
          'Rubona',
          'Susa',
        ],
        Rutabo: [
          'Bugiranteko',
          'Gatonde',
          'Gitwa',
          'Kanka',
          'Mukoma',
          'Nyarugunga',
          'Nyarunazi',
          'Nyirarubayi',
          'Runzenze',
          'Rutabo',
        ],
      },
      Kinihira: {
        Bweramvura: [
          'Bugarura',
          'Gahororo',
          'Gihororo',
          'Kabadende',
          'Nyabivumu',
          'Nyagisenyi',
        ],
        Gitinda: [
          'Kabasanzu',
          'Muremure',
          'Nyagatovu',
          'Nyamagana',
          'Nyarugunga',
          'Nyarusange',
          'Remera',
          'Rubona',
          'Rugarama',
        ],
        Kirwa: [
          'Gasharu',
          'Kabareshya',
          'Muyange',
          'Nyarubuye',
          'Rukeri',
          'Sunzu',
          'Wimana',
        ],
        Muyunzwe: [
          'Gasiza',
          'Muyunzwe',
          'Nyamirambo',
          'Nyarubumbiro',
          'Nyarutovu',
          'Ruhuha',
        ],
        Nyakogo: [
          'Buhanda',
          'Bweramana',
          'Gashirabwoba',
          'Kibirizi',
          'Rusizi',
          'Shamba',
        ],
        Rukina: [
          'Dusenyi',
          'Kabacuzi',
          'Kabirizi',
          'Kabuga',
          'Munini',
          'Murinzi',
        ],
      },
      Mbuye: {
        Cyanza: ['Kabungo', 'Murambi', 'Nyamikoni', 'Rwamiko', 'Wimana'],
        Gisanga: [
          'Bienvenue',
          'Gisanga',
          'Gishari',
          'Karama',
          'Kavumu',
          'Nyarugenge',
          'Sabudari',
          'Sahara',
        ],
        Kabuga: [
          'Kabuga',
          'Kinyinya',
          'Kirwa',
          'Mpungwe',
          'Musenyi',
          'Nyabisindu',
          'Nyakabanda',
          'Nyamutarama',
          'Rugarama',
          'Rwinkuba',
        ],
        Kizibere: [
          'Bereshi',
          'Biraro',
          'Bunyeshywa',
          'Kangoma',
          'Kivumu',
          'Kizibere',
          'Mayunzwe',
          'Nyamiyaga',
          'Rebero',
          'Ruhuha',
        ],
        Mbuye: [
          'Buremera',
          'Cyeru',
          'Cyobe',
          'Kamurema',
          'Kanyinya',
          'Kinyambo',
          'Ruyenzi',
          'Rwimposha',
        ],
        Mwendo: [
          'Cyanika',
          'Gafunzo',
          'Gasanganya',
          'Gatare',
          'Giticyuma',
          'Ipate',
          'Kabuga',
          'Karama',
          'Karusizi',
          'Kavumu',
          'Kidoma',
          'Mataba',
          'Vunga',
        ],
        Nyakarekare: [
          'Bereshi',
          'Jari',
          'Kigabiro',
          'Nyakarekare',
          'Nyaruyonga',
          'Rubona',
          'Ruyenzi',
          'Vugiza',
        ],
      },
      Mwendo: {
        Gafunzo: [
          'Kagarama',
          'Kajevuba',
          'Kimburu',
          'Nyamigina',
          'Nyamugari',
          'Ruhamagariro',
          'Rutagara',
        ],
        Gishweru: ['Kanzu', 'Mabanza', 'Nyakabuye', 'Nyakizu', 'Rubona'],
        Kamujisho: ['Bugaramantare', 'Gakomeye', 'Gitwa', 'Nyarusange'],
        Kigarama: [
          'Gisiza',
          'Gitaraga',
          'Kabacuzi',
          'Kaburinga',
          'Kamuganga',
          'Kamuzimanganya',
          'Kivumu',
        ],
        Kubutare: ['Buhoro', 'Dusego', 'Gasyogogo', 'Karambo'],
        Mutara: [
          'Bunyankungu',
          'Gashiru',
          'Kabiha',
          'Kakarima',
          'Mbunduye',
          'Murambi',
          'Nyabisindu',
        ],
        Nyabibugu: [
          'Kiganira',
          'Ntongwe',
          'Nyarutovu',
          'Nyaruvumu',
          'Rukeri',
          'Ryakabunga',
        ],
        Saruheshyi: ['Buhigiro', 'Gaseke', 'Gasharu', 'Rugasari', 'Ruhondo'],
      },
      Ntongwe: {
        Gako: [
          'Cyimana',
          'Gikoma',
          'Kamakara',
          'Kantwari',
          'Nyabuhuzu',
          'Nyabyugi',
          'Nyamahwa',
        ],
        Kareba: ['Kavumu', 'Kibatsi', 'Marimba', 'Ruko'],
        Kayenzi: ['Kanyete', 'Kirwa', 'Ntungamo', 'Nyagatovu', 'Nyamigende'],
        Kebero: [
          'Cyeru',
          'Gasuna',
          'Kaburanjwiri',
          'Nyabigunzu',
          'Nyabitare',
          'Nyacyonga',
          'Ruko',
        ],
        Nyagisozi: ['Karama', 'Nyamirama', 'Nyarusange'],
        Nyakabungo: [
          'Byimana',
          'Gacuriro',
          'Kamaraba',
          'Karama',
          'Kigabiro',
          'Kintore',
          'Mutima',
          'Nyamirama',
        ],
        Nyarurama: [
          'Gahunga',
          'Gikoni',
          'Kamaraba',
          'Karama',
          'Mukoni',
          'Munini',
          'Nyamirambo',
          'Nyarugenge',
          'Nyarwahi',
          'Ruhuha',
          'Rwakajuju',
          'Rwintama',
        ],
      },
      Ruhango: {
        Buhoro: [
          'Buhoro',
          'Gako',
          'Kabeza',
          'Kantama',
          'Karambo',
          'Muhororo I',
          'Muhororo II',
          'Ntinyinshi',
          'Nyagasozi',
          'Nyangandika',
          'Nyarutovu',
          'Rwinkuba',
        ],
        Bunyogombe: [
          'Bugarura',
          'Busego',
          'Gacoko',
          'Gishegesha',
          'Kabega',
          'Kamugaru',
          'Kamugaza',
          'Karehe',
          'Kasemahundo',
          'Kavumu',
          'Kigabiro',
          'Kigarama',
          'Murehe',
          'Nyabibugu',
          'Nyabisindu',
          'Remera',
          'Rubazi',
          'Rusebeya',
          'Rwankuba',
        ],
        Gikoma: [
          'Gatengeri',
          'Gikumba',
          'Karama',
          'Murambi',
          'Nangurugomo',
          'Nyarusange',
          'Rebero',
          'Rubiha',
          'Rurembo',
          'Ryabonyinka',
          'Wimana',
        ],
        Munini: [
          'Bisambu',
          'Bugari',
          'Bwiza',
          'Cyeshero',
          'Gahama',
          'Gaseke',
          'Gataka',
          'Gitwa',
          'Kabaja',
          'Kaburanjwiri',
          'Kanazi',
          'Kibingo',
          'Kigaga',
          'Kirima',
          'Kiruhura',
          'Munini',
          'Muremera',
          'Nyabinyenga',
          'Nyinya',
          'Ruhuha',
          'Rwezamenyo',
        ],
        Musamo: [
          'Cana',
          'Gaseke',
          'Jokoma',
          'Kabere',
          'Kamabare',
          'Kinama',
          'Kinkene',
          'Musamo',
          'Mwali',
          'Rwinkuba',
          'Rwinyege',
          'Ryanyiranda',
          'Wimana',
        ],
        Nyamagana: [
          'Bumbogo',
          'Butare I',
          'Butare II',
          'Bwangacumu',
          'Gataka',
          'Gatengezi',
          'Gutamba',
          'Kamabano',
          'Kigabiro',
          'Kigimbu',
          'Kinama',
          'Mabera',
          'Mujyejuru I',
          'Mujyejuru II',
          'Murinzi',
          'Ngurukizi',
          'Ntungamo',
          'Nyabihanga',
          'Nyagasozi',
          'Nyamagana',
          'Nyamugari',
          'Nyarusange I',
          'Nyarusange II',
          'Ruhango',
          'Ruhuha',
        ],
        Rwoga: [
          'Bihome',
          'Bugarama',
          'Bunyogombe',
          'Bushenyi',
          'Gasharu',
          'Gatebe',
          'Kabambati',
          'Kangoga',
          'Kavumu',
          'Kibiraro',
          'Muyange',
          'Mwezi',
          'Nyabisindu',
          'Ruhango',
          'Rwinkuba',
          'Rwoga',
        ],
        Tambwe: [
          'Buterana',
          'Mubuga',
          'Nyamugari I',
          'Nyamugari II',
          'Nyundo',
          'Ruduha I',
          'Ruduha II',
          'Rugarama',
          'Rugondo',
          'Tambwe',
        ],
      },
    },
  },
}